POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog 1",
  "author": "No idea",
  "url": "http://blog1.example.com",
  "likes": 125,
  "userId": "615c49ee4428a3182c65dcc6"
}