POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlbm5pYWsiLCJpZCI6IjYxNWM0OWVlNDQyOGEzMTgyYzY1ZGNjNiIsImlhdCI6MTYzMzUyNTQyOX0.0YdFoOBaYDkgJ_8GEwpXo8cccUwYEb9xjIrtO9jLpwQ

{
  "title": "Blog 4",
  "author": "Sin ideas del ID",
  "url": "http://blog4.example.com",
  "likes": 13
}